jv_web:
    resource: "@JVWebBundle/Resources/config/routing.yml"
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'

jv_task:
    resource: "@JVTaskBundle/Resources/config/routing.yml"
    prefix : /{_locale}/intranet/
    requirements:
        _locale: '%app.locales%'

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix : /{_locale}/intranet/admin/
    requirements:
        _locale: '%app.locales%'
