app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'
        
jv_web:
    resource: "@JVWebBundle/Resources/config/routing.yml"
    prefix : /{_locale}/ 
    requirements:
        _locale: '%app.locales%'

jv_task:
    resource: "@JVTaskBundle/Resources/config/routing.yml"
    prefix : /{_locale}/intranet/
    requirements:
        _locale: '%app.locales%'

fos_user_sec:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix : /{_locale}/intranet/log/
    requirements:
        _locale: '%app.locales%'
        
fos_user_pro:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix : /{_locale}/intranet/log/profile
    requirements:
        _locale: '%app.locales%'
        
fos_user_pas:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix : /{_locale}/intranet/log/profile
    requirements:
        _locale: '%app.locales%'

jv_redirect:
    path: /
    defaults:
        _controller: JVWebBundle:Contact:contact
        path: /{locale_}/index
        permanent: true
