jv_task_user:
    resource: "@JVTaskBundle/Resources/config/routing/user.yml"
    prefix:   /user

jv_task_project:
    resource: "@JVTaskBundle/Resources/config/routing/project.yml"
    prefix:   /project
    
jv_task_category:
    resource: "@JVTaskBundle/Resources/config/routing/category.yml"
    prefix:   /category
    
jv_task_task:
    resource: "@JVTaskBundle/Resources/config/routing/task.yml"
    prefix:   /task

jv_task_type:
    resource: "@JVTaskBundle/Resources/config/routing/type.yml"
    prefix:   /type
    
jv_task_homepage:
    path:     /homepage
    defaults: { _controller: JVTaskBundle:Task:list }

fos_user_security_login_username:
    defaults: { _controller: JVTaskBundle:User:login }
    path:     /login/username
    methods:  [GET|POST]