category_index:
    path:     /
    defaults: { _controller: "JVTaskBundle:Category:index" }
    methods:  GET
    
category_list:
    path:     /
    defaults: { _controller: "JVTaskBundle:Category:list" }
    methods:  GET

category_show:
    path:     /{id}/show
    defaults: { _controller: "JVTaskBundle:Category:show" }
    methods:  GET
    requirements:
        id:  \d+ 

category_new:
    path:     /new
    defaults: { _controller: "JVTaskBundle:Category:new" }
    methods:  [GET, POST]

category_edit:
    path:     /{id}/edit
    defaults: { _controller: "JVTaskBundle:Category:edit" }
    methods:  [GET, POST]
    requirements:
        id:  \d+ 

category_delete:
    path:     /{id}/delete
    defaults: { _controller: "JVTaskBundle:Category:delete" }
    methods:  DELETE
    requirements:
        id:  \d+ 