project_index:
    path:     /
    defaults: { _controller: "JVTaskBundle:Project:list" }
    methods:  GET

project_list:
    path:     /
    defaults: { _controller: "JVTaskBundle:Project:list" }
    methods:  GET
    
project_show:
    path:     /{id}/show
    defaults: { _controller: "JVTaskBundle:Project:show" }
    methods:  GET
    requirements:
        id:  \d+ 

project_new:
    path:     /new
    defaults: { _controller: "JVTaskBundle:Project:new" }
    methods:  [GET, POST]

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "JVTaskBundle:Project:edit" }
    methods:  [GET, POST]
    requirements:
        id:  \d+ 

project_delete:
    path:     /{id}/delete
    defaults: { _controller: "JVTaskBundle:Project:delete" }
    methods:  DELETE
    requirements:
        id:  \d+ 
