task_index:
    path:     /
    defaults: { _controller: "JVTaskBundle:Task:list" }
    methods:  GET

task_list:
    path:     /
    defaults: { _controller: "JVTaskBundle:Task:list" }
    methods:  GET

task_show:
    path:     /{id}/show
    defaults: { _controller: "JVTaskBundle:Task:show" }
    methods:  GET
    requirements:
        id:  \d+ 

task_new:
    path:     /new
    defaults: { _controller: "JVTaskBundle:Task:new" }
    methods:  [GET, POST]

task_edit:
    path:     /{id}/edit
    defaults: { _controller: "JVTaskBundle:Task:edit" }
    methods:  [GET, POST]
    requirements:
        id:  \d+ 

task_delete:
    path:     /{id}/delete
    defaults: { _controller: "JVTaskBundle:Task:delete" }
    methods:  DELETE
    requirements:
        id:  \d+ 

task_listByType:
    path:     /{id}/listbytype
    defaults: { _controller: "JVTaskBundle:Task:listByType" }
    methods:  GET
    requirements:
        id:  \d+ 

task_listAllByType:
    path:     /listallbytype
    defaults: { _controller: "JVTaskBundle:Task:listAllByType" }
    methods:  GET
    
task_listByProject:
    path:     /{id}/listbyproject
    defaults: { _controller: "JVTaskBundle:Task:listByProject" }
    methods:  GET
    requirements:
        id:  \d+ 

task_listAllByProject:
    path:     /listallbyproject
    defaults: { _controller: "JVTaskBundle:Task:listAllByProject" }
    methods:  GET

task_listByUser:
    path:     /{id}/listbyuser
    defaults: { _controller: "JVTaskBundle:Task:listByUser" }
    methods:  GET
    requirements:
        id:  \d+

task_listAllByUser:
    path:     /listallbyuser
    defaults: { _controller: "JVTaskBundle:Task:listAllByUser" }
    methods:  GET